"""empty message

Revision ID: 15f3050341b4
Revises: 
Create Date: 2022-12-09 19:16:24.563490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f3050341b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('apellido', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('creacion_fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('imagen', sa.String(length=200), nullable=False),
    sa.Column('horas_jugables', sa.String(length=150), nullable=False),
    sa.Column('sinopsis', sa.String(length=400), nullable=False),
    sa.Column('opinion', sa.String(length=400), nullable=False),
    sa.Column('creacion_fecha', sa.DateTime(), nullable=True),
    sa.Column('privado', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.Column('edad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edad_id'], ['edad.id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=400), nullable=False),
    sa.Column('creacion_fecha', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tema_id', sa.Integer(), nullable=True),
    sa.Column('comentario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentario.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comentario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentario.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('comentario')
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('tema')
    op.drop_table('genero')
    op.drop_table('edad')
    # ### end Alembic commands ###
